project:
  type: website

website:
  title: "Najah's Blog"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Portfolio
        href: portfolio.qmd
      - text: Publications
        href: publications.qmd
      - text: Resume
        target: _blank
        icon: file-pdf-o
        href: docs/Resume_Najah_DS.pdf
      
    right:
      - icon: github
        href: https://github.com/abdulnajah
      - icon: linkedin
        href: https://www.linkedin.com/in/abdulnajah
  google-analytics: "G-FZ5ET06LCD"
  page-footer:
    right: |
      [Contact Najah](mailto:abdulnajahp@gmail.com)
    left: |
      Made with [Quarto](https://quarto.org/)

format:
  html:
    theme: cosmo
    css: styles.css



